version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest@sha256:f08acb30cef8d8077e7b5f912092b40e390d67de845ce09f36bc818d741b5c04
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Gatsby build site
          command: yarn build
      - run:
          name: Tests
          command: yarn jest tests --runInBand --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: coverage
      - run:
          name: Upload test coverage
          command: bash <(curl -s https://codecov.io/bash) -s coverage
