backend:
  name: git-gateway
  branch: add_resources-issue-31

media_folder: content/images
public_folder: /images

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: true, widget: hidden}
      - { name: templateKey, label: Template Key, default: page, widget: hidden}
      - { name: path, label: Path, widget: string, required: false}
      - { name: title, label: Title, widget: string }
      - { name: heroTitle, label: Hero Title, widget: string }
      - { name: heroSubtitle, label: Hero Subtitle, widget: string }
      - { name: heroImage, label: Hero Image, required: false, widget: hidden }
      - { name: heroIsVideo, label: Hero Video, widget: boolean, default: false }
      - { name: body, label: Body, widget: markdown }

  - name: resourceTypes
    label: Resource Types
    label_singular: Resource Type
    folder: content/resources/types
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - { name: title, label: Type, default: true, widget: hidden}
      - { name: labelSingluar, label: Label (Singular), widget: string}
      - { name: label, label: Label (Plural), widget: string}
      - { name: callToAction, label: Call To Action, default: Learn More, widget: string}

  - name: resources
    label: Resources
    label_singular: Resource
    folder: content/resources
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, default: true, widget: string, documentation: must be unique, acts as file name}
      - { name: headline, label: Headline, widget: string}
      - { name: type, label: Type, collection: resourceTypes, searchFields: [title, labelSingluar], widget: string}
